# Generated by Django 5.1.5 on 2025-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenses_amount_alter_expenses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(max_length=256),
        ),
    ]
