# Generated by Django 5.1.5 on 2025-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_category_name_alter_expenses_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='transaction_type',
            field=models.CharField(choices=[('Expenses', 'Expenses'), ('Income', 'Income')], default='Expenses', max_length=10),
            preserve_default=False,
        ),
    ]
