# Generated by Django 5.1.5 on 2025-03-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
