# Generated by Django 5.1.5 on 2025-03-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_category_type_expenses_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterField(
            model_name='expenses',
            name='transaction_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=10),
        ),
    ]
