# Generated by Django 5.1.5 on 2025-04-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_alter_expenses_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('csv', 'CSV Import'), ('receipt', 'Receipt Scan')], default='manual', max_length=20),
        ),
    ]
