# Generated by Django 5.1.5 on 2025-03-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0003_userpreference_monthly_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='monthly_budget',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='savings_goal',
        ),
    ]
