# Generated by Django 5.1.5 on 2025-02-25 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0002_alter_income_amount_alter_income_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=256),
        ),
    ]
