# Generated by Django 5.1.5 on 2025-03-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0004_income_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='income_receipts/'),
        ),
    ]
